/* eslint-disable prettier/prettier */
export enum CategoriesAnime {
  ACTION = 'Action',
  ADVENTURE = 'Adventure',
  COMEDY = 'Comedy',
  DRAMA = 'Drama',
  FANTASY = 'Fantasy',
  HORROR = 'Horror',
  MYSTERY = 'Mystery',
  ROMANCE = 'Romance',
  SCIFI = 'Science Fiction',
  SHONEN = 'Shonen',
  SHOJO = 'Shojo',
  SUPERNATURAL = 'Supernatural',
  THRILLER = 'Thriller',
  PSYCHOLOGICAL = 'Psychological',
  MECHA = 'Mecha',
  MAGIC = 'Magic',
  HISTORICAL = 'Historical',
  SPORTS = 'Sports',
  SLICE_OF_LIFE = 'Slice of Life',
  MUSIC = 'Music',
  MARTIAL_ARTS = 'Martial Arts',
  DEMONS = 'Demons',
  SUPERPOWER = 'Superpower',
  ECCHI = 'Ecchi',
  HAREM = 'Harem',
  SPACE = 'Space',
  MILITARY = 'Military',
  POLICE = 'Police',
  VAMPIRE = 'Vampire',
  SAMURAI = 'Samurai',
  GAME = 'Game',
  SCHOOL = 'School',
}